name: Build

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
    tags-ignore:
      - "v[0-9]+.*"

jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [Windows, MacOS]

        include:
          - name: Windows
            os: windows-latest
          - name: MacOS
            os: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Run "cargo check"
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run "cargo test"
        uses: actions-rs/cargo@v1
        with:
          command: test
