name: Publish

on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  release-build:
    name: Release build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: github.event.base_ref == 'refs/heads/master' # Ignore version tags outside of "master" branch
    strategy:
      matrix:
        name: [Windows, MacOS]

        include:
          - name: Windows
            os: windows-latest
            artifact_name: target/release/stayawake.exe
            asset_name: stayawake-windows
          - name: MacOS
            os: macos-latest
            artifact_name: target/release/stayawake
            asset_name: stayawake-macos

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Run "cargo test"
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run "cargo build --release"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload binary to GitHub artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: release-build
    if: github.event.base_ref == 'refs/heads/master' # Ignore version tags outside of "master" branch
    steps:
      - name: Download all binary assets
        uses: actions/download-artifact@v2

      - name: Rename downloaded binary assets
        run: |
          mkdir releases
          mv stayawake-windows/stayawake.exe releases/stayawake-windows.exe
          mv stayawake-macos/stayawake releases/stayawake-macos

      - name: Publish to GitHub Releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            releases/stayawake-windows.exe
            releases/stayawake-macos
